AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Racing Santander - PRUEBA SIN BALANCEADOR
  Una sola instancia EC2 con WordPress para probar conectividad

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey
    Description: Par de claves SSH

  DBPassword:
    Type: String
    NoEcho: true
    Default: Racing2026
    Description: Contraseña para RDS

Resources:
  # VPC Simple
  RacingVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.200.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Racing-VPC-Test

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Racing-IGW-Test

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref RacingVPC
      InternetGatewayId: !Ref InternetGateway

  # Subnet Pública
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RacingVPC
      CidrBlock: 10.200.10.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Racing-Public-Subnet-Test

  # Subnet Privada para RDS
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RacingVPC
      CidrBlock: 10.200.20.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: Racing-Private-A-Test

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RacingVPC
      CidrBlock: 10.200.21.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: Racing-Private-B-Test

  # Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref RacingVPC
      Tags:
        - Key: Name
          Value: Racing-Public-RT-Test

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Security Group para WordPress (permite HTTP y SSH)
  WordPressSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Racing-WordPress-Test-SG
      GroupDescription: Permite HTTP y SSH desde Internet
      VpcId: !Ref RacingVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP desde Internet
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH desde Internet
      Tags:
        - Key: Name
          Value: Racing-WordPress-Test-SG

  # Security Group para RDS
  DatabaseSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Racing-Database-Test-SG
      GroupDescription: Permite MySQL desde WordPress
      VpcId: !Ref RacingVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WordPressSG
          Description: MySQL desde WordPress
      Tags:
        - Key: Name
          Value: Racing-Database-Test-SG

  # RDS Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group para RDS
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      Tags:
        - Key: Name
          Value: Racing-DB-SubnetGroup-Test

  # RDS MariaDB
  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: racing-test-db
      Engine: mariadb
      EngineVersion: '10.11'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      StorageType: gp3
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      DBName: wordpress
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DatabaseSG
      PubliclyAccessible: false
      MultiAZ: false
      BackupRetentionPeriod: 7
      Tags:
        - Key: Name
          Value: Racing-Test-DB

  # Instancia EC2 con WordPress
  WordPressInstance:
    Type: AWS::EC2::Instance
    DependsOn: RDSInstance
    Properties:
      ImageId: ami-0c7217cdde317cfec
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref WordPressSG
      Tags:
        - Key: Name
          Value: Racing-WordPress-Test
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          exec > >(tee /var/log/user-data.log)
          exec 2>&1

          echo "[$(date)] === INICIO CONFIGURACION WORDPRESS ==="

          # Actualizar sistema
          echo "[$(date)] Actualizando sistema..."
          dnf update -y

          # Instalar Apache y PHP
          echo "[$(date)] Instalando Apache y PHP..."
          dnf install -y httpd php php-mysqlnd php-fpm php-json php-gd wget tar mariadb105

          # Descargar WordPress
          echo "[$(date)] Descargando WordPress..."
          cd /tmp
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz

          # Copiar WordPress
          echo "[$(date)] Configurando WordPress..."
          cp -r wordpress/* /var/www/html/

          # Configurar wp-config.php
          cat > /var/www/html/wp-config.php <<'EOF'
          <?php
          define('DB_NAME', 'wordpress');
          define('DB_USER', 'admin');
          define('DB_PASSWORD', '${DBPassword}');
          define('DB_HOST', '${RDSInstance.Endpoint.Address}');
          define('DB_CHARSET', 'utf8');
          define('DB_COLLATE', '');

          define('AUTH_KEY',         'put your unique phrase here');
          define('SECURE_AUTH_KEY',  'put your unique phrase here');
          define('LOGGED_IN_KEY',    'put your unique phrase here');
          define('NONCE_KEY',        'put your unique phrase here');
          define('AUTH_SALT',        'put your unique phrase here');
          define('SECURE_AUTH_SALT', 'put your unique phrase here');
          define('LOGGED_IN_SALT',   'put your unique phrase here');
          define('NONCE_SALT',       'put your unique phrase here');

          \$table_prefix = 'wp_';
          define('WP_DEBUG', false);

          if ( ! defined( 'ABSPATH' ) ) {
              define( 'ABSPATH', __DIR__ . '/' );
          }

          require_once ABSPATH . 'wp-settings.php';
          EOF

          # Permisos
          chown -R apache:apache /var/www/html
          chmod -R 755 /var/www/html

          # Crear página de prueba
          cat > /var/www/html/test.html <<'TESTEOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Racing Test</title>
              <style>
                  body { font-family: Arial; text-align: center; margin-top: 100px; background: #f0f0f0; }
                  h1 { color: #008000; }
                  .box { background: white; padding: 30px; margin: 20px auto; max-width: 600px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
              </style>
          </head>
          <body>
              <div class="box">
                  <h1>✅ Racing Santander - Servidor Funcionando</h1>
                  <p><strong>Hostname:</strong> $(hostname)</p>
                  <p><strong>IP Privada:</strong> $(hostname -I)</p>
                  <p><strong>Fecha:</strong> $(date)</p>
                  <hr>
                  <p>WordPress instalado en: <a href="/">/</a></p>
                  <p>Base de datos: ${RDSInstance.Endpoint.Address}</p>
              </div>
          </body>
          </html>
          TESTEOF

          # Iniciar Apache
          echo "[$(date)] Iniciando Apache..."
          systemctl start httpd
          systemctl enable httpd

          # Verificar
          echo "[$(date)] Verificando Apache..."
          systemctl status httpd

          echo "[$(date)] === CONFIGURACION COMPLETADA ==="
          echo "[$(date)] Accede a http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)/"
          echo "[$(date)] Página de prueba: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)/test.html"

Outputs:
  WordPressURL:
    Description: URL de acceso directo a WordPress
    Value: !Sub 'http://${WordPressInstance.PublicIp}'

  TestPageURL:
    Description: Página de prueba
    Value: !Sub 'http://${WordPressInstance.PublicIp}/test.html'

  WordPressIP:
    Description: IP pública de la instancia
    Value: !GetAtt WordPressInstance.PublicIp

  SSHCommand:
    Description: Comando SSH para conectar
    Value: !Sub 'ssh -i vockey.pem ec2-user@${WordPressInstance.PublicIp}'

  RDSEndpoint:
    Description: Endpoint de RDS
    Value: !GetAtt RDSInstance.Endpoint.Address

  LogCommand:
    Description: Ver log del UserData
    Value: !Sub 'ssh -i vockey.pem ec2-user@${WordPressInstance.PublicIp} "sudo tail -f /var/log/user-data.log"'
