AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Racing Santander - Functional & Commented CloudFormation Template

  Intent: provide a functional, minimal, and secure baseline for deploying
  WordPress (ALB + ASG + EFS + RDS) with clear comments and optional DB import.

  Notes:
    - No default DB password (must be provided at deploy time, NoEcho).
    - LabInstanceProfile is created here (SSM + limited Describe permissions).
    - Importing initial SQL is optional via parameter `ImportSQL`.

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey
    Description: SSH key pair name for instances (recommended to restrict SSH using AdminCIDR)

  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0c7217cdde317cfec
    Description: AMI ID for your region (Amazon Linux 2 or RHEL9 compatible with dnf)

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: MariaDB 'admin' password (NO DEFAULT — required at stack creation)

  WordPressMinSize:
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 4

  WordPressMaxSize:
    Type: Number
    Default: 4
    MinValue: 2
    MaxValue: 10

  AdminCIDR:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR allowed to access admin SSH (recommended to change to your office/home IP)

  ImportSQL:
    Type: String
    Default: "false"
    AllowedValues: ["true","false"]
    Description: If true, a temporary instance will import the SQL file into RDS

  SQLSourceURL:
    Type: String
    Default: "https://raw.githubusercontent.com/sleuzau01/ASIR-Reto-Equipo3/main/estadio_racing_bares.sql"
    Description: URL to the SQL dump to import when ImportSQL=true

Conditions:
  CreateDBImporter: !Equals [ !Ref ImportSQL, "true" ]

Resources:
  # ---------------------------------------------------------------------------
  # Networking (VPC + public/private subnets + minimal routing)
  # ---------------------------------------------------------------------------
  RacingVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.200.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Racing-VPC

  RacingInternetGateway:
    Type: AWS::EC2::InternetGateway

  RacingIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref RacingVPC
      InternetGatewayId: !Ref RacingInternetGateway

  RacingPublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RacingVPC
      CidrBlock: 10.200.10.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  RacingPublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RacingVPC
      CidrBlock: 10.200.11.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true

  RacingPrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RacingVPC
      CidrBlock: 10.200.20.0/24
      AvailabilityZone: !Select [0, !GetAZs '']

  RacingPrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RacingVPC
      CidrBlock: 10.200.21.0/24
      AvailabilityZone: !Select [1, !GetAZs '']

  # Public route table and associations (internet access for public subnets)
  RacingPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref RacingVPC

  RacingPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: RacingIGWAttachment
    Properties:
      RouteTableId: !Ref RacingPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref RacingInternetGateway

  PublicSubnetARouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref RacingPublicSubnetA
      RouteTableId: !Ref RacingPublicRouteTable

  PublicSubnetBRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref RacingPublicSubnetB
      RouteTableId: !Ref RacingPublicRouteTable

  # Single NAT Gateway for simplicity (placed in PublicSubnetA). Private subnets use NAT for internet egress.
  RacingNatEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  RacingNatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt RacingNatEip.AllocationId
      SubnetId: !Ref RacingPublicSubnetA

  RacingPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref RacingVPC

  RacingPrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RacingPrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref RacingNatGateway

  PrivateSubnetARouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref RacingPrivateSubnetA
      RouteTableId: !Ref RacingPrivateRouteTable

  PrivateSubnetBRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref RacingPrivateSubnetB
      RouteTableId: !Ref RacingPrivateRouteTable

  # ---------------------------------------------------------------------------
  # Security Groups (minimal, explicit comments)
  # ---------------------------------------------------------------------------
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP (ALB)
      VpcId: !Ref RacingVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  AdminSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Admin access (SSH) — restrict with AdminCIDR
      VpcId: !Ref RacingVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AdminCIDR

  WordPressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: WordPress instances (HTTP from ALB)
      VpcId: !Ref RacingVPC

  WordPressIngressFromALB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref WordPressSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup

  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EFS NFS access from WordPress instances
      VpcId: !Ref RacingVPC

  EFSSGIngressFromWordpress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EFSSecurityGroup
      IpProtocol: tcp
      FromPort: 2049
      ToPort: 2049
      SourceSecurityGroupId: !Ref WordPressSecurityGroup

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MariaDB access from WordPress and Admin
      VpcId: !Ref RacingVPC

  DBIngressFromWordpress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DatabaseSecurityGroup
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref WordPressSecurityGroup

  DBIngressFromAdmin:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DatabaseSecurityGroup
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref AdminSecurityGroup

  # ---------------------------------------------------------------------------
  # IAM role & instance profile for instances (SSM + limited describe permissions)
  # ---------------------------------------------------------------------------
  LabInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: DescribeReadOnly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:DescribeLoadBalancers
                  - rds:DescribeDBInstances
                  - ec2:DescribeInstances
                Resource: '*'

  LabInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref LabInstanceRole

  # ---------------------------------------------------------------------------
  # EFS — shared wp-content
  # ---------------------------------------------------------------------------
  WordPressEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose

  EFSMountTargetA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref WordPressEFS
      SubnetId: !Ref RacingPrivateSubnetA
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSMountTargetB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref WordPressEFS
      SubnetId: !Ref RacingPrivateSubnetB
      SecurityGroups:
        - !Ref EFSSecurityGroup

  # ---------------------------------------------------------------------------
  # RDS MariaDB: Multi-AZ across the private subnets
  # ---------------------------------------------------------------------------
  RacingDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnets for RDS (Multi-AZ)
      SubnetIds:
        - !Ref RacingPrivateSubnetA
        - !Ref RacingPrivateSubnetB

  RacingMariaDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: racing-mariadb
      Engine: mariadb
      EngineVersion: '10.11'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp3
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      DBName: estadio_racing_bares
      DBSubnetGroupName: !Ref RacingDBSubnetGroup
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      MultiAZ: true

  # ---------------------------------------------------------------------------
  # ALB + Target Group
  # ---------------------------------------------------------------------------
  RacingLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
        - !Ref RacingPublicSubnetA
        - !Ref RacingPublicSubnetB
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup

  WordPressTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref RacingVPC
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPath: /wp-admin/install.php
      Matcher:
        HttpCode: '200,301,302'

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref RacingLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WordPressTargetGroup

  # ---------------------------------------------------------------------------
  # Launch Template + ASG for WordPress instances
  #  - uses LabInstanceProfile so SSM can be used for maintenance
  #  - installs SSM agent, Apache, PHP and mounts EFS
  # ---------------------------------------------------------------------------
  WordPressLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    DependsOn:
      - RacingMariaDBInstance
      - WordPressEFS
    Properties:
      LaunchTemplateName: Racing-WordPress-LaunchTemplate-Functional
      LaunchTemplateData:
        ImageId: !Ref ImageId
        InstanceType: t3.small
        KeyName: !Ref KeyName
        IamInstanceProfile:
          Name: !Ref LabInstanceProfile
        SecurityGroupIds:
          - !Ref WordPressSecurityGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: Racing-WordPress-Instance
              - Key: ManagedBy
                Value: AutoScaling
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -e
            exec > >(tee /var/log/wordpress-setup.log)
            exec 2>&1

            # Ensure SSM agent available (some AMIs preinstall it, but this guarantees it)
            if ! command -v amazon-ssm-agent >/dev/null 2>&1; then
              dnf install -y amazon-ssm-agent || true
            fi
            systemctl enable --now amazon-ssm-agent || true

            dnf update -y || true
            dnf install -y httpd php php-mysqlnd php-gd php-xml php-mbstring amazon-efs-utils wget || true

            # Download and install WordPress (idempotent)
            mkdir -p /var/www/html
            cd /var/www/html
            if [ ! -f index.php ]; then
              wget -q https://wordpress.org/latest.tar.gz
              tar -xzf latest.tar.gz --strip-components=1
              rm -f latest.tar.gz
            fi

            # Mount EFS to wp-content, preserve existing files if any
            mkdir -p /var/www/html/wp-content
            echo "${WordPressEFS}.efs.${AWS::Region}.amazonaws.com:/ /var/www/html/wp-content nfs4 nfsvers=4.1,_netdev 0 0" >> /etc/fstab || true
            mount -a -t nfs4 || true

            # Configure wp-config.php (replace placeholders)
            if [ -f wp-config-sample.php ] && [ ! -f wp-config.php ]; then
              cp wp-config-sample.php wp-config.php
              sed -i "s/database_name_here/estadio_racing_bares/" wp-config.php
              sed -i "s/username_here/admin/" wp-config.php
              sed -i "s/password_here/${DBPassword}/" wp-config.php
              sed -i "s/localhost/${RacingMariaDBInstance.Endpoint.Address}/" wp-config.php || true
            fi

            # Make WordPress available on the ALB DNS name
            ALB_DNS=""
            for i in {1..20}; do
              ALB_DNS=$(aws elbv2 describe-load-balancers --names Racing-ALB --query 'LoadBalancers[0].DNSName' --output text --region ${AWS::Region} 2>/dev/null || echo "")
              if [[ -n "$ALB_DNS" && "$ALB_DNS" != "None" ]]; then
                break
              fi
              sleep 6
            done
            if [[ -n "$ALB_DNS" && "$ALB_DNS" != "None" ]]; then
              sed -i "/That's all, stop editing/i\\define('WP_HOME', 'http://$ALB_DNS');" wp-config.php || true
              sed -i "/That's all, stop editing/i\\define('WP_SITEURL', 'http://$ALB_DNS');" wp-config.php || true
            fi

            # Permissions and start Apache
            chown -R apache:apache /var/www/html || true
            find /var/www/html -type d -exec chmod 755 {} \; || true
            find /var/www/html -type f -exec chmod 644 {} \; || true
            systemctl enable --now httpd || true

  WordPressAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: Racing-WordPress-ASG
      VPCZoneIdentifier:
        - !Ref RacingPrivateSubnetA
        - !Ref RacingPrivateSubnetB
      LaunchTemplate:
        LaunchTemplateId: !Ref WordPressLaunchTemplate
        Version: !GetAtt WordPressLaunchTemplate.LatestVersionNumber
      MinSize: !Ref WordPressMinSize
      MaxSize: !Ref WordPressMaxSize
      DesiredCapacity: !Ref WordPressMinSize
      HealthCheckType: ELB
      TargetGroupARNs:
        - !Ref WordPressTargetGroup

  WordPressScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref WordPressAutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 70.0

  # ---------------------------------------------------------------------------
  # Optional: Temporary instance to import SQL into RDS (created only if ImportSQL=true)
  # This instance will run once and shut itself down after success.
  # ---------------------------------------------------------------------------
  DatabaseLoaderInstance:
    Condition: CreateDBImporter
    Type: AWS::EC2::Instance
    DependsOn:
      - RacingMariaDBInstance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      SubnetId: !Ref RacingPrivateSubnetA
      SecurityGroupIds:
        - !Ref WordPressSecurityGroup
      IamInstanceProfile: !Ref LabInstanceProfile
      Tags:
        - Key: Name
          Value: Racing-DB-Loader-TEMP
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          exec > >(tee /var/log/db-import.log)
          exec 2>&1

          dnf install -y mariadb105 wget || true

          echo "Waiting for RDS to be available..."
          until mysql -h ${RacingMariaDBInstance.Endpoint.Address} -u admin -p${DBPassword} -e "SELECT 1;" >/dev/null 2>&1; do
            sleep 10
          done

          echo "Downloading SQL from ${SQLSourceURL}"
          wget -O /tmp/estadio.sql "${SQLSourceURL}"

          echo "Importing SQL to RDS"
          mysql -h ${RacingMariaDBInstance.Endpoint.Address} -u admin -p${DBPassword} < /tmp/estadio.sql

          echo "Import completed. Shutting down instance"
          shutdown -h now || true

Outputs:
  WebsiteURL:
    Description: WordPress URL (ALB)
    Value: !Sub "http://${RacingLoadBalancer.DNSName}"

  DatabaseEndpoint:
    Description: RDS endpoint (use bastion or SSM port forward to access privately)
    Value: !GetAtt RacingMariaDBInstance.Endpoint.Address

  EFSFileSystemID:
    Description: EFS ID for wp-content
    Value: !Ref WordPressEFS

  AutoScalingGroupName:
    Description: AutoScalingGroup name for WordPress
    Value: !Ref WordPressAutoScalingGroup
